apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: oauth-server
  namespace: oauth-server

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml

images:
- name: oauth-server
  newTag: latest

commonLabels:
  app: oauth-server
  environment: production

replicas:
- name: oauth-server
  count: 3

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: oauth-server
    namespace: oauth-server
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"